import os
from detectron2.config import CfgNode as CN

def add_dataset_config(cfg):
  _C = cfg

  _C.MODEL.ROI_HEADS.NUM_OUTPUT_CLASSES = 80
  _C.MODEL.ROI_HEADS.EMBEDDINGS_PATH = ""
  _C.MODEL.ROI_HEADS.EMBEDDINGS_PATH_COCO = ""
  _C.MODEL.ROI_HEADS.LINGUAL_MATRIX_THRESHOLD = 0.05
  _C.MODEL.ROI_HEADS.MASK_NUM_CLASSES = 80

  _C.MODEL.FREEZE_LAYERS = CN()
  _C.MODEL.FREEZE_LAYERS.META_ARCH = []
  _C.MODEL.FREEZE_LAYERS.ROI_HEADS = []

  _C.DATASETS.TYPE = ""
  _C.DATASETS.VISUAL_GENOME = CN()
  _C.DATASETS.VISUAL_GENOME.IMAGES = ''
  _C.DATASETS.VISUAL_GENOME.MAPPING_DICTIONARY = ''
  _C.DATASETS.VISUAL_GENOME.IMAGE_DATA = ''
  _C.DATASETS.VISUAL_GENOME.SG_TRAIN_DATA = ''
  _C.DATASETS.VISUAL_GENOME.SG_VAL_DATA = ''
  _C.DATASETS.VISUAL_GENOME.SG_MAPPER = ''
  _C.DATASETS.VISUAL_GENOME.VG_ATTRIBUTE_H5 = ''
  _C.DATASETS.VISUAL_GENOME.TRAIN_MASKS = ""
  _C.DATASETS.VISUAL_GENOME.TEST_MASKS = ""
  _C.DATASETS.VISUAL_GENOME.VAL_MASKS = ""
  _C.DATASETS.VISUAL_GENOME.CLIPPED = False
  _C.DATASETS.VISUAL_GENOME.PER_CLASS_DATASET = False
  _C.DATASETS.VISUAL_GENOME.BGNN = False

  _C.DATASETS.ACTION_GENOME = CN()
  _C.DATASETS.ACTION_GENOME.ANNOTATIONS = ''
  _C.DATASETS.ACTION_GENOME.FILTER_EMPTY_RELATIONS = True
  _C.DATASETS.ACTION_GENOME.FILTER_DUPLICATE_RELATIONS = True
  _C.DATASETS.ACTION_GENOME.FILTER_NON_OVERLAP = True
  _C.DATASETS.ACTION_GENOME.FORMAT_VID_WISE = False
  _C.DATASETS.ACTION_GENOME.FRAMES = ''
  _C.DATASETS.ACTION_GENOME.VIDEOS = ''
  _C.DATASETS.ACTION_GENOME.NUM_VIDEOS_TRAIN = -1
  _C.DATASETS.ACTION_GENOME.NUM_VIDEOS_VAL = 400
  _C.DATASETS.ACTION_GENOME.VAL_SET_RANDOMIZED = False


  _C.DATASETS.MSCOCO = CN()
  _C.DATASETS.MSCOCO.ANNOTATIONS = ''
  _C.DATASETS.MSCOCO.DATAROOT = ''

  _C.DATASETS.VISUAL_GENOME.FILTER_EMPTY_RELATIONS = True
  _C.DATASETS.VISUAL_GENOME.FILTER_DUPLICATE_RELATIONS = True
  _C.DATASETS.VISUAL_GENOME.FILTER_NON_OVERLAP = True
  _C.DATASETS.VISUAL_GENOME.EXCLUDE_LEFT_RIGHT = False
  _C.DATASETS.VISUAL_GENOME.NUMBER_OF_VALIDATION_IMAGES = 5000
  _C.DATASETS.VISUAL_GENOME.BOX_SCALE = 1024
  _C.DATASETS.VISUAL_GENOME.MAX_NUM_RELATIONS = -1
  _C.DATASETS.VISUAL_GENOME.MAX_NUM_OBJECTS = -1
  _C.DATASETS.VISUAL_GENOME.UNDERSAMPLE_PARAM = 0.7
  _C.DATASETS.VISUAL_GENOME.OVERSAMPLE_PARAM = 0.07

  _C.DATASETS.SEG_DATA_DIVISOR = 1

  _C.DATASETS.TRANSFER = ('coco_train_2014',)
  _C.DATASETS.MASK_TRAIN = ('coco_train_2017',)
  _C.DATASETS.MASK_TEST = ('coco_val_2017',)

  _C.MODEL.DETR = CN()
  _C.MODEL.DETR.NUM_CLASSES = 80
  _C.MODEL.DETR.NUM_RELATION_CLASSES = 50

  # For Segmentation
  _C.MODEL.DETR.FROZEN_WEIGHTS = ''
  _C.MODEL.DETR.FREEZE = False
  _C.MODEL.DETR.SGDET_USE_GT = False

  # LOSS
  _C.MODEL.DETR.COST_CLASS = 1.0
  _C.MODEL.DETR.GIOU_WEIGHT = 2.0
  _C.MODEL.DETR.L1_WEIGHT = 5.0
  _C.MODEL.DETR.FOCAL_ALPHA = 0.25
  _C.MODEL.DETR.DEEP_SUPERVISION = True
  _C.MODEL.DETR.NO_OBJECT_WEIGHT = 0.1
  _C.MODEL.DETR.CLS_WEIGHT = 2.0
  _C.MODEL.DETR.COST_SELECTION = 1.0
  
  
  # RELATION LOSS
  _C.MODEL.DETR.RELATION_LOSS_WEIGHT = 1.0

  # TRANSFORMER
  _C.MODEL.DETR.NAME = 'DETR'
  _C.MODEL.DETR.CRITERION = 'SetCriterion'
  _C.MODEL.DETR.TRANSFORMER = 'Transformer'
  _C.MODEL.DETR.MATCHER = 'HungarianMatcher'
  _C.MODEL.DETR.POSITION_EMBEDDING = 'PositionEmbeddingSine'
  _C.MODEL.DETR.NHEADS = 8
  _C.MODEL.DETR.DROPOUT = 0.1
  _C.MODEL.DETR.DIM_FEEDFORWARD = 2048
  _C.MODEL.DETR.ENC_LAYERS = 6
  _C.MODEL.DETR.DEC_LAYERS = 6
  _C.MODEL.DETR.RELATION_DEC_LAYERS = 4
  _C.MODEL.DETR.OBJECT_DEC_LAYERS = 4
  _C.MODEL.DETR.PRE_NORM = False
  _C.MODEL.DETR.RELATION_HEAD = True
  _C.MODEL.DETR.CLASS_AGNOSTIC_NMS = True
  _C.MODEL.DETR.INTERSECTION_IOU_THRESHOLD = 0.3
  _C.MODEL.DETR.INTERSECTION_IOU_LAMBDA = 1.0
  _C.MODEL.DETR.INTERSECTION_LOSS = False
  _C.MODEL.DETR.NO_REL_WEIGHT = 0.1
  _C.MODEL.DETR.LATER_NMS_THRESHOLD = 0.3
  _C.MODEL.DETR.USE_FREQ_BIAS = True
  _C.MODEL.DETR.NUM_FEATURE_LEVELS = 4
  _C.MODEL.DETR.WITH_BOX_REFINE = False
  _C.MODEL.DETR.TWO_STAGE = False
  _C.MODEL.DETR.TWO_STAGE_NUM_PROPOSALS = 300
  _C.MODEL.DETR.REWEIGHT_RELATIONS = False
  _C.MODEL.DETR.REWEIGHT_USE_LOG = True
  _C.MODEL.DETR.REWEIGHT_REL_EOS_COEF = 0.1
  _C.MODEL.DETR.NEGATIVE_RELATION_FRACTION = 3.0
  _C.MODEL.DETR.MAX_RELATION_PAIRS = 16
  _C.MODEL.DETR.NMS_WEIGHT = 0.2
  _C.MODEL.DETR.BETA = 1000
  _C.MODEL.DETR.MATCHER_TOPK = 1
  _C.MODEL.DETR.OVERSAMPLE_PARAM = 0.07
  _C.MODEL.DETR.UNDERSAMPLE_PARAM = 1.0
  _C.MODEL.DETR.FREEZE_LAYERS = []
  _C.MODEL.DETR.TEST_INDEX = -1

  _C.MODEL.DETR.HIDDEN_DIM = 256
  _C.MODEL.DETR.NUM_OBJECT_QUERIES = 100
  _C.MODEL.DETR.NUM_RELATION_QUERIES = 100
  _C.MODEL.DETR.CREATE_BG_PAIRS = False

  _C.SOLVER.OPTIMIZER = "ADAMW"
  _C.SOLVER.BACKBONE_MULTIPLIER = 0.1
  _C.SOLVER.RELATION_MULTIPLIER = 1.0
  _C.SOLVER.ENTITY_MULTIPLIER = 1.0
  _C.SOLVER.MAX_TO_KEEP = 2
  _C.MODEL.DF_DETR = CN()
  _C.MODEL.DF_DETR.NUM_CLASSES = 80

  # MODEL Variants 
  _C.MODEL.DF_DETR.WITH_BOX_REFINE = False
  _C.MODEL.DF_DETR.TWO_STAGE = False

  # Backbone
  _C.MODEL.DF_DETR.BACKBONE = "resnet50"
  _C.MODEL.DF_DETR.DILATION = False
  _C.MODEL.DF_DETR.POSITIONAL_EMBEDDING = 'sine'
  _C.MODEL.DF_DETR.NUM_FEATURE_LEVELS = 4

  # Transformer
  _C.MODEL.DF_DETR.ENC_LAYERS = 6
  _C.MODEL.DF_DETR.DEC_LAYERS = 6
  _C.MODEL.DF_DETR.DIM_FEEDFORWARD = 1024
  _C.MODEL.DF_DETR.HIDDEN_DIM = 256
  _C.MODEL.DF_DETR.DROPOUT = 0.1
  _C.MODEL.DF_DETR.NHEADS = 8
  _C.MODEL.DF_DETR.NUM_OBJECT_QUERIES = 300
  _C.MODEL.DETR.DEC_N_POINTS = 4
  _C.MODEL.DETR.ENC_N_POINTS = 4

  # Mathcher
  _C.MODEL.DF_DETR.SET_COST_CLASS = 2
  _C.MODEL.DF_DETR.SET_COST_BBOX = 5
  _C.MODEL.DF_DETR.SET_COST_GIOU = 2

  # Loss 
  _C.MODEL.DF_DETR.CLS_LOSS_WEIGHT = 2.
  _C.MODEL.DF_DETR.BBOX_LOSS_WEIGHT = 5.
  _C.MODEL.DF_DETR.GIOU_LOSS_WEIGHT = 2.
  _C.MODEL.DF_DETR.RELATION_LOSS_WEIGHT = 1.
  _C.MODEL.DF_DETR.FOCAL_ALPHA = 0.25
  _C.MODEL.DF_DETR.DEEP_SUPERVISION = True

  # relation part
  _C.MODEL.DF_DETR.RELATION_DEC_LAYERS = 4
  _C.MODEL.DF_DETR.PRE_NORM = False
  _C.MODEL.DF_DETR.RELATION_HEAD = True

  # custom configs
  _C.MODEL.DETR.ONE_TO_MANY = False

  # o2m
  _C.MODEL.DETR.ONE2MANY_SCHEME = 'static'
  _C.MODEL.DETR.ONE2MANY_DYNAMIC_SCHEME = 'min'
  _C.MODEL.DETR.ONE2MANY_K = 1
  _C.MODEL.DETR.MATCH_INDEPENDENT = False
  _C.MODEL.DETR.ONE2MANY_PREDICATE_SCORE = False
  _C.MODEL.DETR.ONE2MANY_PREDICATE_WEIGHT = 1.0

  # grouping
  _C.MODEL.DETR.MULTIPLY_QUERY = 1
  _C.MODEL.DETR.USE_GROUP_MASK = False
  _C.MODEL.DETR.ONLY_PREDICATE_MULTIPLY = False
  _C.MODEL.DETR.NUM_GROUPS = 5

  # wandb
  _C.WANDB = CN()
  _C.WANDB.USE_WANDB = False
  _C.WANDB.ENTITY = 'your_entity'
  _C.WANDB.PROJECT = 'speaq'
  _C.WANDB.GROUP = 'speaq'
  _C.WANDB.EXP_NAME = 'default_exp_name'


def add_scenegraph_config(cfg):
    _C = cfg
    
    _C.GLOVE_DIR = 'glove/'
    _C.DEV_RUN = False
    ###################################################################################################

    _C.MODEL.SCENEGRAPH_ON = True
    _C.MODEL.ROI_BOX_HEAD.TRAIN_ON_PRED_BOXES = True
    _C.MODEL.USE_MASK_ON_NODE = False
    _C.MODEL.ROI_HEADS.OBJECTNESS_THRESH = 0.3
    _C.MODEL.GROUP_NORM = CN()
    _C.MODEL.GROUP_NORM.DIM_PER_GP = -1
    _C.MODEL.GROUP_NORM.NUM_GROUPS = 32
    _C.MODEL.GROUP_NORM.EPSILON = 1e-5 # default: 1e-5
    ###################################################################################################
    _C.MODEL.ROI_SCENEGRAPH_HEAD = CN()
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NAME = 'SceneGraphHead'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MODE = 'predcls'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.REQUIRE_BOX_OVERLAP = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NUM_SAMPLE_PER_GT_REL = 4  # when sample fg relationship from gt, the max number of corresponding proposal pairs
    _C.MODEL.ROI_SCENEGRAPH_HEAD.BATCH_SIZE_PER_IMAGE = 64
    _C.MODEL.ROI_SCENEGRAPH_HEAD.POSITIVE_FRACTION = 0.25
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_GT_BOX = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_GT_OBJECT_LABEL = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NMS_FILTER_DUPLICATES = True
    
    _C.MODEL.SCENEGRAPH_SAMPLER = CN()
    _C.MODEL.SCENEGRAPH_SAMPLER.NAME = "TransformerRelationSampler"

    _C.MODEL.SCENEGRAPH_LOSS = CN()
    _C.MODEL.SCENEGRAPH_LOSS.NAME = "TransformerRelatonLoss"

    _C.MODEL.SCENEGRAPH_POST_PROCESSOR = CN()
    _C.MODEL.SCENEGRAPH_POST_PROCESSOR.NAME = 'TransformerRelationPostProcesser'

    _C.MODEL.ROI_SCENEGRAPH_HEAD.RETURN_SEG_MASKS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.RETURN_SEG_ANNOS = False

    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_VISION = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_BIAS = True
    
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_MASK_ATTENTION = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.MASK_ATTENTION_TYPE = 'Self'
    _C.MODEL.ROI_SCENEGRAPH_HEAD.SIGMOID_ATTENTION = True

    _C.MODEL.ROI_SCENEGRAPH_HEAD.PREDICTOR = "MotifPredictor"
    _C.MODEL.ROI_SCENEGRAPH_HEAD.NUM_CLASSES = 50
    _C.MODEL.ROI_SCENEGRAPH_HEAD.EMBED_DIM = 200
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_DROPOUT_RATE = 0.2
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_HIDDEN_DIM = 512
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_POOLING_DIM = 4096
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_OBJ_LAYER = 1  # assert >= 1
    _C.MODEL.ROI_SCENEGRAPH_HEAD.CONTEXT_REL_LAYER = 1  # assert >= 1
    _C.MODEL.ROI_SCENEGRAPH_HEAD.ADD_GTBOX_TO_PROPOSAL_IN_TRAIN = True
    _C.MODEL.ROI_SCENEGRAPH_HEAD.SEG_BBOX_LOSS_MULTIPLIER = 1.0
    _C.MODEL.ROI_SCENEGRAPH_HEAD.USE_ONLY_FG_PROPOSALS = True

    _C.MODEL.ROI_SCENEGRAPH_HEAD.LABEL_SMOOTHING_LOSS = False
    _C.MODEL.ROI_SCENEGRAPH_HEAD.REL_PROP = [0.01858, 0.00057, 0.00051, 0.00109, 0.00150, 0.00489, 0.00432, 0.02913, 0.00245, 0.00121, 
                                       0.00404, 0.00110, 0.00132, 0.00172, 0.00005, 0.00242, 0.00050, 0.00048, 0.00208, 0.15608,
                                       0.02650, 0.06091, 0.00900, 0.00183, 0.00225, 0.00090, 0.00028, 0.00077, 0.04844, 0.08645,
                                       0.31621, 0.00088, 0.00301, 0.00042, 0.00186, 0.00100, 0.00027, 0.01012, 0.00010, 0.01286,
                                       0.00647, 0.00084, 0.01077, 0.00132, 0.00069, 0.00376, 0.00214, 0.11424, 0.01205, 0.02958]

    _C.MODEL.ROI_SCENEGRAPH_HEAD.ZERO_SHOT_TRIPLETS = 'evaluation/datasets/vg/zeroshot_triplet.pytorch'

    #TransformerContext
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER = CN()
    # for TransformerPredictor only
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.DROPOUT_RATE = 0.1   
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.OBJ_LAYER = 4        
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.REL_LAYER = 2        
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.NUM_HEAD = 8         
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.INNER_DIM = 2048     
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.KEY_DIM = 64         
    _C.MODEL.ROI_SCENEGRAPH_HEAD.TRANSFORMER.VAL_DIM = 64     
    ###################################################################################################
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS = CN()
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.NAME = 'BoxFeatureExtractor'
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_RESOLUTION = 28
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.POOLER_TYPE = 'ROIAlignV2'
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.BOX_FEATURE_MASK = True 
    _C.MODEL.ROI_BOX_FEATURE_EXTRACTORS.CLASS_LOGITS_WITH_MASK = False

    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS = CN()
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.NAME = 'RelationFeatureExtractor'
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.USE_MASK_COMBINER = False
    _C.MODEL.ROI_RELATION_FEATURE_EXTRACTORS.MULTIPLY_LOGITS_WITH_MASKS = True

    # Overlap threshold for an RoI to be considered foreground (if >= FG_IOU_THRESHOLD)
    _C.MODEL.ROI_HEADS.FG_IOU_THRESHOLD = 0.5
    _C.MODEL.ROI_HEADS.REFINE_SEG_MASKS = True
    _C.MODEL.ROI_HEADS.SEGMENTATION_STEP_MASK_REFINE = True

    # Settings for relation testing
    _C.TEST.RELATION = CN()
    _C.TEST.RELATION.REQUIRE_OVERLAP = True
    _C.TEST.RELATION.LATER_NMS_PREDICTION_THRES = 0.3 
    _C.TEST.RELATION.MULTIPLE_PREDS = False
    _C.TEST.RELATION.IOU_THRESHOLD = 0.5


    _C.DATASETS.VISUAL_GENOME.CLIPPED = False
    
    #############################
    _C.TEST.NUM_REL = 1
    _C.TEST.PNMS = False